server:
  port: 8001

spring:
  application:
    name: Java_RestAPI
  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://192.168.99.100:3301/users?useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
